const kanjidata = [
  {
    id: "1",
    type: "kanji",
    character: "一",
    strokes: 1,
    meanings: ["eins"],
    on: ["ichi", "itsu"],
    kun: ["hito-tsu"],
  },
  {
    id: "2",
    type: "kanji",
    character: "二",
    strokes: 2,
    meanings: ["zwei"],
    on: ["ni", "ji"],
    kun: ["futa-tsu"],
  },
  {
    id: "3",
    type: "kanji",
    character: "三",
    strokes: 3,
    meanings: ["drei"],
    on: ["san"],
    kun: ["mit-tsu"],
  },
  {
    id: "4",
    type: "kanji",
    character: "四",
    strokes: 5,
    meanings: ["vier"],
    on: ["san"],
    kun: ["mit-tsu"],
  },
  {
    id: "5",
    type: "kanji",
    character: "五",
    strokes: "4",
    meanings: "fünf",
    on: ["go"],
    kon: ["itsu-tsu"],
  },
  {
    id: "6",
    type: "kanji",
    character: "六",
    strokes: "4",
    meanings: "sechs",
    on: ["roku"],
    kon: ["mut-tsu"],
  },
  {
    id: "7",
    type: "kanji",
    character: "七",
    strokes: "2",
    meanings: "sieben",
    on: ["shichi"],
    kon: ["nana-tsu"],
  },
  {
    id: "8",
    type: "kanji",
    character: "八",
    strokes: "2",
    meanings: "acht",
    on: ["hachi"],
    kon: ["yat-tsu"],
  },
  {
    id: "9",
    type: "kanji",
    character: "九",
    strokes: "2",
    meanings: "neun",
    on: ["ku", "kyū"],
    kon: ["kokono-tsu"],
  },
  {
    id: "10",
    type: "kanji",
    character: "十",
    strokes: "2",
    meanings: "zehn",
    on: ["jū"],
    kon: ["tō"],
  },
  {
    id: "11",
    type: "kanji",
    character: "百",
    strokes: "6",
    meanings: "hundert",
    on: ["hyaku"],
    kon: ["momo"],
  },
  {
    id: "12",
    type: "kanji",
    character: "千",
    strokes: "3",
    meanings: "tausend",
    on: ["sen"],
    kon: ["chi"],
  },
  {
    id: "13",
    type: "kanji",
    character: "上",
    strokes: "3",
    meanings: "oben",
    on: ["jō"],
    kon: ["ue", "kami", "a-geru"],
  },
  {
    id: "14",
    type: "kanji",
    character: "下",
    strokes: "3",
    meanings: "unten",
    on: ["ka", "ge"],
    kon: ["shita", "sa-geru", "kuda-saru"],
  },
  {
    id: "15",
    type: "kanji",
    character: "左",
    strokes: "5",
    meanings: "links",
    on: ["sa"],
    kon: ["hidari"],
  },
  {
    id: "16",
    type: "kanji",
    character: "右",
    strokes: "5",
    meanings: "rechts",
    on: ["u", "yū"],
    kon: ["migi"],
  },
  {
    id: "17",
    type: "kanji",
    character: "中",
    strokes: "4",
    meanings: "innen, Mitte",
    on: ["chū", "jū"],
    kon: ["naka"],
  },
  {
    id: "18",
    type: "kanji",
    character: "大",
    strokes: "3",
    meanings: "groß",
    on: ["dai", "tai"],
    kon: ["ō-kii"],
  },
  {
    id: "19",
    type: "kanji",
    character: "小",
    strokes: "3",
    meanings: "klein",
    on: ["shō"],
    kon: ["chii-sai", "ko", "o"],
  },
  {
    id: "20",
    type: "kanji",
    character: "月",
    strokes: "4",
    meanings: "Monat; Mond",
    on: ["gatsu", "getsu"],
    kon: ["tsuki"],
  },
  {
    id: "21",
    type: "kanji",
    character: "日",
    strokes: "4",
    meanings: "Tag; Sonne",
    on: ["nichi", "jitsu"],
    kon: ["hi", "ka"],
  },
  {
    id: "22",
    type: "kanji",
    character: "年",
    strokes: "6",
    meanings: "Jahr",
    on: ["nen"],
    kon: ["toshi"],
  },
  {
    id: "23",
    type: "kanji",
    character: "早",
    strokes: "6",
    meanings: "früh; schnell",
    on: ["sō", "satsu"],
    kon: ["haya-i"],
  },
  {
    id: "24",
    type: "kanji",
    character: "木",
    strokes: "4",
    meanings: "Baum; Holz",
    on: ["moku", "boku"],
    kon: ["ki"],
  },
  {
    id: "25",
    type: "kanji",
    character: "林",
    strokes: "7",
    meanings: "Hain, Forst",
    on: ["rin"],
    kon: ["hayashi"],
  },
  {
    id: "26",
    type: "kanji",
    character: "山",
    strokes: "3",
    meanings: "Berg",
    on: ["san", "zan"],
    kon: ["yama"],
  },
  {
    id: "27",
    type: "kanji",
    character: "川",
    strokes: "3",
    meanings: "Fluss",
    on: ["sen"],
    kon: ["kawa"],
  },
  {
    id: "28",
    type: "kanji",
    character: "土",
    strokes: "3",
    meanings: "Erde",
    on: ["do", "to"],
    kon: ["tsuchi"],
  },
  {
    id: "29",
    type: "kanji",
    character: "空",
    strokes: "8",
    meanings: "Himmel (vgl. ''sky'')",
    on: ["kū"],
    kon: ["sora", "a-ku", "kara"],
  },
  {
    id: "30",
    type: "kanji",
    character: "田",
    strokes: "5",
    meanings: "Reisfeld",
    on: ["den"],
    kon: ["da", "ta"],
  },
  {
    id: "31",
    type: "kanji",
    character: "天",
    strokes: "4",
    meanings: "Himmel (vgl. ''heaven'')",
    on: ["ten"],
    kon: ["ame", "ama"],
  },
  {
    id: "32",
    type: "kanji",
    character: "生",
    strokes: "5",
    meanings: "Leben; roh",
    on: ["sei", "shō"],
    kon: ["i-kiru", "u-mu", "nama"],
  },
  {
    id: "33",
    type: "kanji",
    character: "花",
    strokes: "7",
    meanings: "Blume",
    on: ["ka"],
    kon: ["hana"],
  },
  {
    id: "34",
    type: "kanji",
    character: "草",
    strokes: "9",
    meanings: "Gras",
    on: ["sō"],
    kon: ["kusa"],
  },
  {
    id: "35",
    type: "kanji",
    character: "虫",
    strokes: "6",
    meanings: "Insekt",
    on: ["chū"],
    kon: ["mushi"],
  },
  {
    id: "36",
    type: "kanji",
    character: "犬",
    strokes: "4",
    meanings: "Hund",
    on: ["ken"],
    kon: ["inu"],
  },
  {
    id: "37",
    type: "kanji",
    character: "人",
    strokes: "2",
    meanings: "Person, Mensch",
    on: ["jin", "nin"],
    kon: ["hito"],
  },
  {
    id: "38",
    type: "kanji",
    character: "名",
    strokes: "6",
    meanings: "Name",
    on: ["mei", "myō"],
    kon: ["na"],
  },
  {
    id: "39",
    type: "kanji",
    character: "女",
    strokes: "3",
    meanings: "Frau",
    on: ["jo", "nyo"],
    kon: ["on'na"],
  },
  {
    id: "40",
    type: "kanji",
    character: "男",
    strokes: "7",
    meanings: "Mann",
    on: ["dan", "nan"],
    kon: ["otoko"],
  },
  {
    id: "41",
    type: "kanji",
    character: "子",
    strokes: "3",
    meanings: "Kind",
    on: ["shi", "su"],
    kon: ["ko"],
  },
  {
    id: "42",
    type: "kanji",
    character: "目",
    strokes: "5",
    meanings: "Auge",
    on: ["moku"],
    kon: ["me"],
  },
  {
    id: "43",
    type: "kanji",
    character: "耳",
    strokes: "6",
    meanings: "Ohr",
    on: ["ji", "ni"],
    kon: ["mimi"],
  },
  {
    id: "44",
    type: "kanji",
    character: "口",
    strokes: "3",
    meanings: "Mund",
    on: ["kō"],
    kon: ["kuchi"],
  },
  {
    id: "45",
    type: "kanji",
    character: "手",
    strokes: "4",
    meanings: "Hand",
    on: ["shu"],
    kon: ["te"],
  },
  {
    id: "46",
    type: "kanji",
    character: "足",
    strokes: "7",
    meanings: "Fuß",
    on: ["soku"],
    kon: ["ashi"],
  },
  {
    id: "47",
    type: "kanji",
    character: "見",
    strokes: "7",
    meanings: "sehen",
    on: ["ken", "gen"],
    kon: ["mi-ru"],
  },
  {
    id: "48",
    type: "kanji",
    character: "音",
    strokes: "9",
    meanings: "Ton, Geräusch",
    on: ["on"],
    kon: ["ne", "oto"],
  },
  {
    id: "49",
    type: "kanji",
    character: "力",
    strokes: "2",
    meanings: "Kraft",
    on: ["riki", "ryoku"],
    kon: ["chikara"],
  },
  {
    id: "50",
    type: "kanji",
    character: "気",
    strokes: "6",
    meanings: "Luft; Geist, Seele; Stimmung",
    on: ["ki", "ke"],
    kon: ["iki"],
  },
  {
    id: "51",
    type: "kanji",
    character: "円",
    strokes: "4",
    meanings: "Yen; Kreis",
    on: ["en"],
    kon: ["maru"],
  },
  {
    id: "52",
    type: "kanji",
    character: "入",
    strokes: "2",
    meanings: "hineingehen",
    on: ["nyū"],
    kon: ["hai-ru", "i-ru "],
  },
  {
    id: "53",
    type: "kanji",
    character: "出",
    strokes: "5",
    meanings: "herauskommen",
    on: ["shutsu"],
    kon: ["de-ru"],
  },
  {
    id: "54",
    type: "kanji",
    character: "立",
    strokes: "5",
    meanings: "aufstehen",
    on: ["ritsu"],
    kon: ["ta-tsu"],
  },
  {
    id: "55",
    type: "kanji",
    character: "休",
    strokes: "6",
    meanings: "ausruhen",
    on: ["kyū"],
    kon: ["yasu-mu"],
  },
  {
    id: "56",
    type: "kanji",
    character: "先",
    strokes: "6",
    meanings: "vorher; vorne",
    on: ["sen"],
    kon: ["saki"],
  },
  {
    id: "57",
    type: "kanji",
    character: "夕",
    strokes: "3",
    meanings: "Abend",
    on: ["seki"],
    kon: ["yū"],
  },
  {
    id: "58",
    type: "kanji",
    character: "本",
    strokes: "5",
    meanings: "Buch; Ursprung",
    on: ["hon"],
    kon: ["moto"],
  },
  {
    id: "59",
    type: "kanji",
    character: "文",
    strokes: "4",
    meanings: "Text",
    on: ["bun", "mon"],
    kon: ["fumi"],
  },
  {
    id: "60",
    type: "kanji",
    character: "字",
    strokes: "6",
    meanings: "Schriftzeichen",
    on: ["ji"],
    kon: ["aza"],
  },
  {
    id: "61",
    type: "kanji",
    character: "学",
    strokes: "8",
    meanings: "lernen",
    on: ["gaku"],
    kon: ["mana-bu"],
  },
  {
    id: "62",
    type: "kanji",
    character: "校",
    strokes: "10",
    meanings: "Schule",
    on: ["kō"],
  },
  {
    id: "63",
    type: "kanji",
    character: "村",
    strokes: "7",
    meanings: "Dorf",
    on: ["son"],
    kon: ["mura"],
  },
  {
    id: "64",
    type: "kanji",
    character: "町",
    strokes: "7",
    meanings: "Stadt",
    on: ["chō"],
    kon: ["machi"],
  },
  {
    id: "65",
    type: "kanji",
    character: "森",
    strokes: "11",
    meanings: "Wald",
    on: ["shin"],
    kon: ["mori"],
  },
  {
    id: "66",
    type: "kanji",
    character: "正",
    strokes: "5",
    meanings: "richtig, gerecht",
    on: ["sei", "shō "],
    kon: ["tada-shii", "masa"],
  },
  {
    id: "67",
    type: "kanji",
    character: "水",
    strokes: "4",
    meanings: "Wasser",
    on: ["sui"],
    kon: ["mizu"],
  },
  {
    id: "68",
    type: "kanji",
    character: "火",
    strokes: "4",
    meanings: "Feuer",
    on: ["ka"],
    kon: ["hi"],
  },
  {
    id: "69",
    type: "kanji",
    character: "玉",
    strokes: "5",
    meanings: "Edelstein",
    on: ["gyoku"],
    kon: ["tama"],
  },
  {
    id: "70",
    type: "kanji",
    character: "王",
    strokes: "4",
    meanings: "König",
    on: ["ō"],
    kon: ["kimi"],
  },
  {
    id: "71",
    type: "kanji",
    character: "石",
    strokes: "5",
    meanings: "Stein",
    on: ["seki", "koku"],
    kon: ["ishi"],
  },
  {
    id: "72",
    type: "kanji",
    character: "竹",
    strokes: "6",
    meanings: "Bambus",
    on: ["chiku"],
    kon: ["take"],
  },
  {
    id: "73",
    type: "kanji",
    character: "糸",
    strokes: "6",
    meanings: "Faden",
    on: ["shi"],
    kon: ["ito"],
  },
  {
    id: "74",
    type: "kanji",
    character: "貝",
    strokes: "7",
    meanings: "Muschel",
    on: ["bai"],
    kon: ["kai"],
  },
  {
    id: "75",
    type: "kanji",
    character: "車",
    strokes: "7",
    meanings: "Fahrzeug",
    on: ["sha"],
    kon: ["kuruma"],
  },
  {
    id: "76",
    type: "kanji",
    character: "金",
    strokes: "8",
    meanings: "Gold; Geld",
    on: ["kin"],
    kon: ["kane", "kana"],
  },
  {
    id: "77",
    type: "kanji",
    character: "雨",
    strokes: "8",
    meanings: "Regen",
    on: ["u"],
    kon: ["ame", "ama"],
  },
  {
    id: "78",
    type: "kanji",
    character: "赤",
    strokes: "7",
    meanings: "rot",
    on: ["seki"],
    kon: ["aka"],
  },
  {
    id: "79",
    type: "kanji",
    character: "青",
    strokes: "8",
    meanings: "blau",
    on: ["sei", "shō"],
    kon: ["ao"],
  },
  {
    id: "80",
    type: "kanji",
    character: "白",
    strokes: "5",
    meanings: "weiß",
    on: ["haku"],
    kon: ["shiro", "shira"],
  },
];